package Kratzer.JavaFXDemos;// Handle events generated by the keyboard.

import javafx.application.*;
import javafx.scene.*;
import javafx.stage.*;
import javafx.scene.layout.*;
import javafx.scene.control.*;
import javafx.event.*;
import javafx.geometry.*;
import javafx.scene.input.*;

public class KeyEventDemo extends Application {

    Label prompt;
    Label showKey;

    public static void main(String[] args) {

        // Start the JavaFX application by calling launch(). 
        launch(args);
    }

    // Override the start() method. 
    public void start(Stage myStage) {

        // Give the stage a title. 
        myStage.setTitle("Handle Keyboard Events");

        // Use a FlowPane for the root node. In this case, 
        // the horizontal gap is 10. 
        FlowPane rootNode = new FlowPane(Orientation.VERTICAL, 0, 10);

        // Center the controls in the scene. 
        rootNode.setAlignment(Pos.CENTER);

        // Create a scene. 
        Scene myScene = new Scene(rootNode, 300, 100);

        // Set the scene on the stage. 
        myStage.setScene(myScene);

        // Create labels. 
        prompt = new Label("Press a key.");
        showKey = new Label("");

        // Handle a key typed event on the scene. 
        myScene.setOnKeyTyped(new EventHandler<KeyEvent>() {
            public void handle(KeyEvent ke) {
                showKey.setText("You typed " + ke.getCharacter());
            }
        });

        // Handle a key pressed event on the scene. 
        myScene.setOnKeyPressed(new EventHandler<KeyEvent>() {
            public void handle(KeyEvent ke) {
                switch (ke.getCode()) {
                    case RIGHT:
                        showKey.setText("You pressed Right Arrow.");
                        break;
                    case LEFT:
                        showKey.setText("You pressed Left Arrow.");
                        break;
                    case F10:
                        showKey.setText("You pressed F10.");
                        break;
                    case ALT:
                        showKey.setText("You pressed Alt.");
                        break;
                }
            }
        });

        // Add the labels to the scene graph. 
        rootNode.getChildren().addAll(prompt, showKey);

        // Show the stage and its scene. 
        myStage.show();
    }
}
